name: Restart Workflow

on:
  repository_dispatch:
    types: [restart]

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger self again
        if: ${{ success() }}
        shell: pwsh
        run: |
          $uri = "https://api.github.com/repos/Godnight1006/CursorRegister/actions/workflows/cursor_register.yml/dispatches"
          $body = @{
            ref = "main"
            inputs = @{
              number = "23"
              max_workers = "3"
              ingest_to_oneapi = "true"
              upload_artifact = "true"
            }
          } | ConvertTo-Json

          Invoke-RestMethod -Uri $uri -Method Post -Body $body -ContentType "application/json" -Headers @{
            Authorization = "token ${{ secrets.GITHUB_TOKEN }}"
            Accept = "application/vnd.github.v3+json"
          }
